### ISSUE TITLE
Not working well with QuickShopPlugin

### ISSUE THREAD

**Issue by Leoparking** [Interlink-Media/Sierra#16]
**Server logs url**
There is nothing on the console when the player operates it
**Screenshot of detection**
see below
**Output of /version**
1.20.1

**Output of /sierra version**
1.3.2.1

**Whats your client version**
1.20.1

First, create a Quick SHop vending box. Right click on the notice board above, and some settings buttons will be displayed in the chat bar. Then you will find that clicking on the buttons above does not respond
My current solution is also very simple——Remove Sierra and do not use it
<img width="956" alt="image" src="https://github.com/user-attachments/assets/315bfb2c-d0e2-480f-9853-f6d421ff37f3">

![image](https://github.com/user-attachments/assets/9cef055c-25c3-4de3-a6fa-3fcca881c293)

**Comment by SquareCodeFX** [comment]
This version of sierra is outdated and unsupported. Use latest sierra to receive support

**Comment by Leoparking** [comment]
> 此版本的 Sierra 已过时且不受支持。使用最新的 Sierra 获得支持

我记得是最新版啊

**Comment by SquareCodeFX** [comment]
Okay try the new version and write me again if the issue still exists

**Comment by Leoparking** [comment]
> 好的，尝试新版本，如果问题仍然存在，请再次写信给我

<img width="430" alt="image" src="https://github.com/user-attachments/assets/e39fc76d-5e71-4bf6-9c0a-f511f1e3b8d1">
What's the meaning of this?

**Comment by Leoparking** [comment]
<img width="630" alt="image" src="https://github.com/user-attachments/assets/9346032f-c9b1-43e5-9d1c-48d3e42411e3">
How to modify the threshold？I searched for 5000 but there was no response

**Comment by Leoparking** [comment]
https://github.com/Interlink-Media/Sierra/issues/18
