### ISSUE TITLE
As soon as a player enters the game and send a message, they will be kicked out immediately

### ISSUE THREAD

**Issue by Leoparking** [Interlink-Media/Sierra#18]
**Server logs url**

**Screenshot of detection**
<img width="480" alt="image" src="https://github.com/user-attachments/assets/5bf23813-17db-4d6d-904d-54e13781656f">
<img width="411" alt="image" src="https://github.com/user-attachments/assets/8d77184e-6b19-4f52-981b-7140e9128f18">

**Output of /version**
1.20.1
**Output of /sierra version**
1.4.5
**Whats your client version**
1.20.1

I think it's because I added default chat prefixes to everyone (containing a lot of placeholder information, which may result in larger data packets than usual)
Such as  [player_server][level] [player_world][level] <name> ......

**Comment by SquareCodeFX** [comment]
Increase the limit in your configuration.

**Comment by Leoparking** [comment]
> Increase the limit in your configuration.

?
<img width="298" alt="image" src="https://github.com/user-attachments/assets/97702bf1-69f0-4d6e-81cb-364d9e66ecf1">
?
