### ISSUE TITLE
391444

### ISSUE THREAD

**Issue by tanto-mc** [Interlink-Media/Sierra#19]
Plugin kicks player when player clicks in any Inventory (e.g. menu) to item, if in PersistentDataContainer of item be variable type String contains '-' symbol

**Comment by SquareCodeFX** [comment]
I need more information. I need console logs and mitigation and alert messages and a screenshot from that item you clicked on

**Comment by tanto-mc** [comment]
![image](https://github.com/user-attachments/assets/a6253c6d-0eeb-46c4-bb13-67a065034100)
![image](https://github.com/user-attachments/assets/ca922e4b-7f5f-4064-8bad-d0443d305487)
It kicks when clicking on any object where there is a "-" symbol

**Comment by SquareCodeFX** [comment]
Increase the limit in your configuration. Search for 5000 and increase it. "generic-packet-limit". And remove your review on SpigotMC. The review section is not there for any issues. Even if it's a 5 star review.
