### ISSUE TITLE
无法进入游戏

### ISSUE THREAD

**Issue by Leoparking** [Interlink-Media/Sierra#5]
**Description**
<img width="1174" alt="image" src="https://github.com/Interlink-Media/Sierra/assets/141799770/5d464846-0e65-4c6d-9c52-e74db89796fa">
**The specific performance is the same as another plugin**
https://github.com/HaHaWTH/ClientBoomer/issues/3

**Steps to reproduce**
1. Install on the cloud VPS host

2. Start Minecraft server

3. Unable to access the server

4. Remove the plugin

5. Restart

6. You can enter now
**Sierra Version**1.3.2.1

**Comment by SquareCodeFX** [comment]
I need more information for this. Console logs, a list of plugins on the server, your Java version, your server's operating system, and your client and server version.

**Comment by Leoparking** [comment]
> 我需要更多信息。控制台日志、服务器上的插件列表、Java 版本、服务器的操作系统以及客户端和服务器版本。

There is no message on the console, only player disconnection and link messages exist
The loading phase of the plugin is completely normal
The following images show all plugins except Sierra
<img width="661" alt="image" src="https://github.com/Interlink-Media/Sierra/assets/141799770/26917a7d-1e28-4982-92d9-ab8d45d7c135">

In addition, when we use commands to load it in the game, it can also cause players to disconnect and never scan server information

### This is the background information when the player attempts to re-enter the game (I just saw a unrelated plugins)
`[21:39:19 WARN]: [HolographicDisplays] Unexpected error while modifying the chan
nel pipeline.
java.util.NoSuchElementException: packet_handler
        at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChanne
lPipeline.java:1073) ~[netty-transport-4.1.82.Final.jar%23175!/:4.1.82.Final]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipel
ine.java:248) ~[netty-transport-4.1.82.Final.jar%23175!/:4.1.82.Final]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipel
ine.java:237) ~[netty-transport-4.1.82.Final.jar%23175!/:4.1.82.Final]
        at me.filoghost.holographicdisplays.nms.v1_20_R1.VersionNMSManager.lambd
a$injectPacketListener$0(VersionNMSManager.java:82) ~[?:?]
        at me.filoghost.holographicdisplays.nms.v1_20_R1.VersionNMSManager.lambd
a$modifyPipeline$2(VersionNMSManager.java:120) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventE
xecutor.java:174) ~[netty-common-4.1.82.Final.jar%23172!/:4.1.82.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEv
entExecutor.java:167) ~[netty-common-4.1.82.Final.jar%23172!/:4.1.82.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(Single
ThreadEventExecutor.java:470) ~[netty-common-4.1.82.Final.jar%23172!/:4.1.82.Fin
al]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-
transport-4.1.82.Final.jar%23175!/:4.1.82.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThread
EventExecutor.java:997) ~[netty-common-4.1.82.Final.jar%23172!/:4.1.82.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java
:74) ~[netty-common-4.1.82.Final.jar%23172!/:4.1.82.Final]
        at java.lang.Thread.run(Unknown Source) [?:?]
[21:39:19 WARN]: java.util.NoSuchElementException: packet_handler
[21:39:19 WARN]:        at dev.geco.gsit.mcv.v1_20.util.PackageUtil.registerPlay
er(PackageUtil.java:54)
[21:39:19 WARN]:        at dev.geco.gsit.events.PlayerEvents.PJoiE(PlayerEvents.
java:32)
[21:39:20 INFO]: The_Leopard_King已离线  当前还有0在线
[21:39:20 WARN]: handleDisconnection() called twice
[21:39:21 INFO]: [NoSpawnChunks] Unloading chunks in world world...`

**Comment by SquareCodeFX** [comment]
Please send me the output of /about ProtocolLib

**Comment by Leoparking** [comment]
> Please send me the output of /about ProtocolLib

![Screenshot_2024-05-29-09-12-13-282_com.oray.sunlogin-edit.jpg](https://github.com/Interlink-Media/Sierra/assets/141799770/b9a711ed-c6d3-4031-ba56-bab284b46053)

**Comment by SquareCodeFX** [comment]
Please send me the output of /version. I would like to know what spigot that is

**Comment by Leoparking** [comment]
> Please send me the output of /version. I would like to know what spigot that is

Ok
this is he output

Mohist version 1.20.1-604 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT, Forge version 47.2.20, NeoForge version 47.1.79)

**Comment by SquareCodeFX** [comment]
This software is not supported by us, and we do not plan to offer support for it. We exclusively support software based on Bukkit/Spigot. We do support Spigot forks such as Paper, but any further modification of the software is not supported by us.

**Comment by Leoparking** [comment]
> This software is not supported by us, and we do not plan to offer support for it. We exclusively support software based on Bukkit/Spigot. We do support Spigot forks such as Paper, but any further modification of the software is not supported by us.
😭
