### ISSUE TITLE
Deluxemenu bug (Imposible to use custom menus)

### ISSUE THREAD

**Issue by LuckserSky34** [Interlink-Media/Sierra#6]
**Server logs url**
No

**Screenshot of detection**
[Link](https://cdn.discordapp.com/attachments/1127352913807806685/1246201437885825216/image.png?ex=665b8708&is=665a3588&hm=759294ccb6f2e27861b5df466b9562b669fcc58804fad66e8d95f6af5fbd23b1&)

**Output of /version**
1.20.4

**Output of /sierra version**
last

**Whats your client version**
Lunar client 1.20.4

**Comment by SquareCodeFX** [comment]
You clicked on a skull didn't you?

**Comment by LuckserSky34** [comment]
yes

**Comment by LuckserSky34** [comment]
i only use deluxemenu adding custom heads
![image](https://github.com/Interlink-Media/Sierra/assets/53704877/3aab20f8-d650-4a2f-bd3c-166762d96f66)

**Comment by SquareCodeFX** [comment]
Try this version
[File.zip](https://github.com/user-attachments/files/15523214/File.zip)

**Comment by SquareCodeFX** [comment]
If that works, please send me the exact name of the plugin so that I can write a compatibility system to switch it automatically.

**Comment by LuckserSky34** [comment]
its fixed now, thanks, thuis is the plugin i using https://github.com/HelpChat/DeluxeMenus

**Comment by SquareCodeFX** [comment]
All right, the bug is fixed in the next release version
